@startuml
'https://plantuml.com/class-diagram
package java.lang.Object #DEFDF5{
    class Class{}
    package java.lang.reflect    #DDDFF0{
        class Constructor{
        }

        class Parameter{
        }

        class Method{
        }

        class Executable{
        }

        class AccessibleObject{
            }
        interface AnnotatedElement{
            }
        AccessibleObject <|. AnnotatedElement
        AccessibleObject <|-- Executable
        Executable <|-- Method
        Executable <|-- Constructor
    }
    Class *-- AccessibleObject
    Class *-- Parameter
}


@enduml